01:30:10 AM: CRITICAL [task_models.py:19] MONGODB_USER variable not found
01:51:41 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
01:51:41 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
01:51:41 AM: INFO [_internal.py:96]  * Restarting with stat
01:51:41 AM: WARNING [_internal.py:96]  * Debugger is active!
01:51:41 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
01:54:22 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
01:54:22 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
01:54:22 AM: INFO [_internal.py:96]  * Restarting with stat
01:54:22 AM: WARNING [_internal.py:96]  * Debugger is active!
01:54:22 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
01:54:34 AM: CRITICAL [task_services.py:13] Error fetching all tasks from the database: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
01:54:34 AM: ERROR [task_routes.py:24] Error fetching data from the database: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/routes/task_routes.py", line 22, in get_tasks
    return jsonify(self.tasks), 200
           ^^^^^^^^^^^^^^^^^^^
  File "/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/venv/lib/python3.12/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/venv/lib/python3.12/site-packages/flask/json/provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/venv/lib/python3.12/site-packages/flask/json/provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.12/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/venv/lib/python3.12/site-packages/flask/json/provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable
01:54:34 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 01:54:34] "[35m[1mGET /api/tasks HTTP/1.1[0m" 500 -
02:21:47 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/models/task_models.py', reloading
02:21:47 AM: INFO [_internal.py:96]  * Restarting with stat
02:21:47 AM: WARNING [_internal.py:96]  * Debugger is active!
02:21:47 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:21:56 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
02:21:56 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
02:21:56 AM: INFO [_internal.py:96]  * Restarting with stat
02:21:56 AM: WARNING [_internal.py:96]  * Debugger is active!
02:21:56 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:22:20 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 02:22:20] "GET /api/tasks HTTP/1.1" 200 -
02:25:09 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/models/task_models.py', reloading
02:25:09 AM: INFO [_internal.py:96]  * Restarting with stat
02:25:10 AM: WARNING [_internal.py:96]  * Debugger is active!
02:25:10 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:25:17 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/models/task_models.py', reloading
02:25:17 AM: INFO [_internal.py:96]  * Restarting with stat
02:25:18 AM: WARNING [_internal.py:96]  * Debugger is active!
02:25:18 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:25:24 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
02:25:24 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
02:25:24 AM: INFO [_internal.py:96]  * Restarting with stat
02:25:24 AM: WARNING [_internal.py:96]  * Debugger is active!
02:25:24 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:25:30 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 02:25:30] "GET /api/tasks HTTP/1.1" 200 -
02:27:49 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/models/task_models.py', reloading
02:27:50 AM: INFO [_internal.py:96]  * Restarting with stat
02:27:50 AM: WARNING [_internal.py:96]  * Debugger is active!
02:27:50 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:28:03 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
02:28:03 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
02:28:03 AM: INFO [_internal.py:96]  * Restarting with stat
02:28:03 AM: WARNING [_internal.py:96]  * Debugger is active!
02:28:03 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:28:15 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 02:28:15] "GET /api/tasks HTTP/1.1" 200 -
02:59:23 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
02:59:23 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
02:59:23 AM: INFO [_internal.py:96]  * Restarting with stat
02:59:23 AM: WARNING [_internal.py:96]  * Debugger is active!
02:59:23 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
02:59:30 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 02:59:30] "GET /api/tasks HTTP/1.1" 200 -
03:19:39 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/schemas/task_schemas.py', reloading
03:19:39 AM: INFO [_internal.py:96]  * Restarting with stat
03:19:39 AM: WARNING [_internal.py:96]  * Debugger is active!
03:19:39 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
03:19:41 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/app.py', reloading
03:19:42 AM: INFO [_internal.py:96]  * Restarting with stat
03:19:42 AM: WARNING [_internal.py:96]  * Debugger is active!
03:19:42 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
03:20:20 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03:20:20 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
03:20:20 AM: INFO [_internal.py:96]  * Restarting with stat
03:20:21 AM: WARNING [_internal.py:96]  * Debugger is active!
03:20:21 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
03:20:30 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 03:20:30] "GET /api/tasks HTTP/1.1" 200 -
03:27:14 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/models/task_models.py', reloading
03:27:15 AM: INFO [_internal.py:96]  * Restarting with stat
03:27:15 AM: WARNING [_internal.py:96]  * Debugger is active!
03:27:15 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
03:27:23 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/models/task_models.py', reloading
03:27:24 AM: INFO [_internal.py:96]  * Restarting with stat
03:27:24 AM: WARNING [_internal.py:96]  * Debugger is active!
03:27:24 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
03:27:30 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03:27:30 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
03:27:30 AM: INFO [_internal.py:96]  * Restarting with stat
03:27:31 AM: WARNING [_internal.py:96]  * Debugger is active!
03:27:31 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
03:27:45 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 03:27:45] "GET /api/tasks HTTP/1.1" 200 -
03:32:12 AM: INFO [_internal.py:96] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03:32:12 AM: INFO [_internal.py:96] [33mPress CTRL+C to quit[0m
03:32:12 AM: INFO [_internal.py:96]  * Restarting with stat
03:32:12 AM: WARNING [_internal.py:96]  * Debugger is active!
03:32:12 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
03:32:27 AM: INFO [_internal.py:96] 127.0.0.1 - - [07/Dec/2023 03:32:27] "GET /api/tasks HTTP/1.1" 200 -
03:35:54 AM: INFO [_internal.py:96]  * Detected change in '/home/icddgs/Desktop/SistemasDistribuidos/Api/TaskAPI/services/task_services.py', reloading
03:35:54 AM: INFO [_internal.py:96]  * Restarting with stat
03:35:55 AM: WARNING [_internal.py:96]  * Debugger is active!
03:35:55 AM: INFO [_internal.py:96]  * Debugger PIN: 462-129-208
